public func fileExtension(forMime mime: String) -> String? {
	// Removing .lowercased() fixes the issue.
	// Compiling with -Xllvm -sil-disable-pass=GuaranteedARCOpts also fixes the issue.
	switch mime.lowercased() {
	case "application/andrew-inset":
		return "ez"
	case "application/applixware":
		return "aw"
	case "application/atom+xml":
		return "atom"
	case "application/atomcat+xml":
		return "atomcat"
	case "application/atomsvc+xml":
		return "atomsvc"
	case "application/ccxml+xml":
		return "ccxml"
	case "application/cdmi-capability":
		return "cdmia"
	case "application/cdmi-container":
		return "cdmic"
	case "application/cdmi-domain":
		return "cdmid"
	case "application/cdmi-object":
		return "cdmio"
	case "application/cdmi-queue":
		return "cdmiq"
	case "application/cu-seeme":
		return "cu"
	case "application/davmount+xml":
		return "davmount"
	case "application/docbook+xml":
		return "dbk"
	case "application/dssc+der":
		return "dssc"
	case "application/dssc+xml":
		return "xdssc"
	case "application/ecmascript":
		return "es"
	case "application/emma+xml":
		return "emma"
	case "application/epub+zip":
		return "epub"
	case "application/exi":
		return "exi"
	case "application/font-tdpfr":
		return "pfr"
	case "application/gml+xml":
		return "gml"
	case "application/gpx+xml":
		return "gpx"
	case "application/gxf":
		return "gxf"
	case "application/hyperstudio":
		return "stk"
	case "application/inkml+xml":
		return "ink"
	case "application/ipfix":
		return "ipfix"
	case "application/java-archive":
		return "jar"
	case "application/java-serialized-object":
		return "ser"
	case "application/java-vm":
		return "class"
	case "application/javascript":
		return "js"
	case "application/json":
		return "json"
	case "application/jsonml+json":
		return "jsonml"
	case "application/lost+xml":
		return "lostxml"
	case "application/mac-binhex40":
		return "hqx"
	case "application/mac-compactpro":
		return "cpt"
	case "application/mads+xml":
		return "mads"
	case "application/marc":
		return "mrc"
	case "application/marcxml+xml":
		return "mrcx"
	case "application/mathematica":
		return "nb"
	case "application/mathml+xml":
		return "mathml"
	case "application/mbox":
		return "mbox"
	case "application/mediaservercontrol+xml":
		return "mscml"
	case "application/metalink+xml":
		return "metalink"
	case "application/metalink4+xml":
		return "meta4"
	case "application/mets+xml":
		return "mets"
	case "application/mods+xml":
		return "mods"
	case "application/mp21":
		return "m21"
	case "application/mp4":
		return "mp4s"
	case "application/msword":
		return "doc"
	case "application/mxf":
		return "mxf"
	case "application/octet-stream":
		return "bin"
	case "application/oda":
		return "oda"
	case "application/oebps-package+xml":
		return "opf"
	case "application/ogg":
		return "ogx"
	case "application/omdoc+xml":
		return "omdoc"
	case "application/onenote":
		return "one"
	case "application/oxps":
		return "oxps"
	case "application/patch-ops-error+xml":
		return "xer"
	case "application/pdf":
		return "pdf"
	case "application/pgp-encrypted":
		return "pgp"
	case "application/pgp-signature":
		return "pgp"
	case "application/pics-rules":
		return "prf"
	case "application/pkcs10":
		return "p10"
	case "application/pkcs7-mime":
		return "p7m"
	case "application/pkcs7-signature":
		return "p7s"
	case "application/pkcs8":
		return "p8"
	case "application/pkix-attr-cert":
		return "ac"
	case "application/pkix-cert":
		return "cer"
	case "application/pkix-crl":
		return "crl"
	case "application/pkix-pkipath":
		return "pkipath"
	case "application/pkixcmp":
		return "pki"
	case "application/pls+xml":
		return "pls"
	case "application/postscript":
		return "ps"
	case "application/prs.cww":
		return "cww"
	case "application/pskc+xml":
		return "pskcxml"
	case "application/rdf+xml":
		return "rdf"
	case "application/reginfo+xml":
		return "rif"
	case "application/relax-ng-compact-syntax":
		return "rnc"
	case "application/resource-lists+xml":
		return "rl"
	case "application/resource-lists-diff+xml":
		return "rld"
	case "application/rls-services+xml":
		return "rs"
	case "application/rpki-ghostbusters":
		return "gbr"
	case "application/rpki-manifest":
		return "mft"
	case "application/rpki-roa":
		return "roa"
	case "application/rsd+xml":
		return "rsd"
	case "application/rss+xml":
		return "rss"
	case "application/rtf":
		return "rtf"
	case "application/sbml+xml":
		return "sbml"
	case "application/scvp-cv-request":
		return "scq"
	case "application/scvp-cv-response":
		return "scs"
	case "application/scvp-vp-request":
		return "spq"
	case "application/scvp-vp-response":
		return "spp"
	case "application/sdp":
		return "sdp"
	case "application/set-payment-initiation":
		return "setpay"
	case "application/set-registration-initiation":
		return "setreg"
	case "application/shf+xml":
		return "shf"
	case "application/smil+xml":
		return "smi"
	case "application/sparql-query":
		return "rq"
	case "application/sparql-results+xml":
		return "srx"
	case "application/srgs":
		return "gram"
	case "application/srgs+xml":
		return "grxml"
	case "application/sru+xml":
		return "sru"
	case "application/ssdl+xml":
		return "ssdl"
	case "application/ssml+xml":
		return "ssml"
	case "application/tei+xml":
		return "tei"
	case "application/thraud+xml":
		return "tfi"
	case "application/timestamped-data":
		return "tsd"
	case "application/vnd.3gpp.pic-bw-large":
		return "plb"
	case "application/vnd.3gpp.pic-bw-small":
		return "psb"
	case "application/vnd.3gpp.pic-bw-var":
		return "pvb"
	case "application/vnd.3gpp2.tcap":
		return "tcap"
	case "application/vnd.3m.post-it-notes":
		return "pwn"
	case "application/vnd.accpac.simply.aso":
		return "aso"
	case "application/vnd.accpac.simply.imp":
		return "imp"
	case "application/vnd.acucobol":
		return "acu"
	case "application/vnd.acucorp":
		return "atc"
	case "application/vnd.adobe.air-application-installer-package+zip":
		return "air"
	case "application/vnd.adobe.formscentral.fcdt":
		return "fcdt"
	case "application/vnd.adobe.fxp":
		return "fxp"
	case "application/vnd.adobe.xdp+xml":
		return "xdp"
	case "application/vnd.adobe.xfdf":
		return "xfdf"
	case "application/vnd.ahead.space":
		return "ahead"
	case "application/vnd.airzip.filesecure.azf":
		return "azf"
	case "application/vnd.airzip.filesecure.azs":
		return "azs"
	case "application/vnd.amazon.ebook":
		return "azw"
	case "application/vnd.americandynamics.acc":
		return "acc"
	case "application/vnd.amiga.ami":
		return "ami"
	case "application/vnd.android.package-archive":
		return "apk"
	case "application/vnd.anser-web-certificate-issue-initiation":
		return "cii"
	case "application/vnd.anser-web-funds-transfer-initiation":
		return "fti"
	case "application/vnd.antix.game-component":
		return "atx"
	case "application/vnd.apple.installer+xml":
		return "mpkg"
	case "application/vnd.apple.mpegurl":
		return "m3u8"
	case "application/vnd.aristanetworks.swi":
		return "swi"
	case "application/vnd.astraea-software.iota":
		return "iota"
	case "application/vnd.audiograph":
		return "aep"
	case "application/vnd.blueice.multipass":
		return "mpm"
	case "application/vnd.bmi":
		return "bmi"
	case "application/vnd.businessobjects":
		return "rep"
	case "application/vnd.chemdraw+xml":
		return "cdxml"
	case "application/vnd.chipnuts.karaoke-mmd":
		return "mmd"
	case "application/vnd.cinderella":
		return "cdy"
	case "application/vnd.claymore":
		return "cla"
	case "application/vnd.cloanto.rp9":
		return "rp9"
	case "application/vnd.clonk.c4group":
		return "c4g"
	case "application/vnd.cluetrust.cartomobile-config":
		return "c11amc"
	case "application/vnd.cluetrust.cartomobile-config-pkg":
		return "c11amz"
	case "application/vnd.commonspace":
		return "csp"
	case "application/vnd.contact.cmsg":
		return "cdbcmsg"
	case "application/vnd.cosmocaller":
		return "cmc"
	case "application/vnd.crick.clicker":
		return "clkx"
	case "application/vnd.crick.clicker.keyboard":
		return "clkk"
	case "application/vnd.crick.clicker.palette":
		return "clkp"
	case "application/vnd.crick.clicker.template":
		return "clkt"
	case "application/vnd.crick.clicker.wordbank":
		return "clkw"
	case "application/vnd.criticaltools.wbs+xml":
		return "wbs"
	case "application/vnd.ctc-posml":
		return "pml"
	case "application/vnd.cups-ppd":
		return "ppd"
	case "application/vnd.curl.car":
		return "car"
	case "application/vnd.curl.pcurl":
		return "pcurl"
	case "application/vnd.dart":
		return "dart"
	case "application/vnd.data-vision.rdz":
		return "rdz"
	case "application/vnd.dece.data":
		return "uvf"
	case "application/vnd.dece.ttml+xml":
		return "uvt"
	case "application/vnd.dece.unspecified":
		return "uvx"
	case "application/vnd.dece.zip":
		return "uvz"
	case "application/vnd.denovo.fcselayout-link":
		return "fe_launch"
	case "application/vnd.dna":
		return "dna"
	case "application/vnd.dolby.mlp":
		return "mlp"
	case "application/vnd.dpgraph":
		return "dpg"
	case "application/vnd.dreamfactory":
		return "dfac"
	case "application/vnd.ds-keypoint":
		return "kpxx"
	case "application/vnd.dvb.ait":
		return "ait"
	case "application/vnd.dvb.service":
		return "svc"
	case "application/vnd.dynageo":
		return "geo"
	case "application/vnd.ecowin.chart":
		return "mag"
	case "application/vnd.enliven":
		return "nml"
	case "application/vnd.epson.esf":
		return "esf"
	case "application/vnd.epson.msf":
		return "msf"
	case "application/vnd.epson.quickanime":
		return "qam"
	case "application/vnd.epson.salt":
		return "slt"
	case "application/vnd.epson.ssf":
		return "ssf"
	case "application/vnd.eszigno3+xml":
		return "es3"
	case "application/vnd.ezpix-album":
		return "ez2"
	case "application/vnd.ezpix-package":
		return "ez3"
	case "application/vnd.fdf":
		return "fdf"
	case "application/vnd.fdsn.mseed":
		return "mseed"
	case "application/vnd.fdsn.seed":
		return "seed"
	case "application/vnd.flographit":
		return "gph"
	case "application/vnd.fluxtime.clip":
		return "ftc"
	case "application/vnd.framemaker":
		return "fm"
	case "application/vnd.frogans.fnc":
		return "fnc"
	case "application/vnd.frogans.ltf":
		return "ltf"
	case "application/vnd.fsc.weblaunch":
		return "fsc"
	case "application/vnd.fujitsu.oasys":
		return "oas"
	case "application/vnd.fujitsu.oasys2":
		return "oa2"
	case "application/vnd.fujitsu.oasys3":
		return "oa3"
	case "application/vnd.fujitsu.oasysgp":
		return "fg5"
	case "application/vnd.fujitsu.oasysprs":
		return "bh2"
	case "application/vnd.fujixerox.ddd":
		return "ddd"
	case "application/vnd.fujixerox.docuworks":
		return "xdw"
	case "application/vnd.fujixerox.docuworks.binder":
		return "xbd"
	case "application/vnd.fuzzysheet":
		return "fzs"
	case "application/vnd.genomatix.tuxedo":
		return "txd"
	case "application/vnd.geogebra.file":
		return "ggb"
	case "application/vnd.geogebra.tool":
		return "ggt"
	case "application/vnd.geometry-explorer":
		return "gex"
	case "application/vnd.geonext":
		return "gxt"
	case "application/vnd.geoplan":
		return "g2w"
	case "application/vnd.geospace":
		return "g3w"
	case "application/vnd.gmx":
		return "gmx"
	case "application/vnd.google-earth.kml+xml":
		return "kml"
	case "application/vnd.google-earth.kmz":
		return "kmz"
	case "application/vnd.grafeq":
		return "gqf"
	case "application/vnd.groove-account":
		return "gac"
	case "application/vnd.groove-help":
		return "ghf"
	case "application/vnd.groove-identity-message":
		return "gim"
	case "application/vnd.groove-injector":
		return "grv"
	case "application/vnd.groove-tool-message":
		return "gtm"
	case "application/vnd.groove-tool-template":
		return "tpl"
	case "application/vnd.groove-vcard":
		return "vcg"
	case "application/vnd.hal+xml":
		return "hal"
	case "application/vnd.handheld-entertainment+xml":
		return "zmm"
	case "application/vnd.hbci":
		return "hbci"
	case "application/vnd.hhe.lesson-player":
		return "les"
	case "application/vnd.hp-hpgl":
		return "hpgl"
	case "application/vnd.hp-hpid":
		return "hpid"
	case "application/vnd.hp-hps":
		return "hps"
	case "application/vnd.hp-jlyt":
		return "jlt"
	case "application/vnd.hp-pcl":
		return "pcl"
	case "application/vnd.hp-pclxl":
		return "pclxl"
	case "application/vnd.hydrostatix.sof-data":
		return "sfd-hdstx"
	case "application/vnd.ibm.minipay":
		return "mpy"
	case "application/vnd.ibm.modcap":
		return "afp"
	case "application/vnd.ibm.rights-management":
		return "irm"
	case "application/vnd.ibm.secure-container":
		return "sc"
	case "application/vnd.iccprofile":
		return "icc"
	case "application/vnd.igloader":
		return "igl"
	case "application/vnd.immervision-ivp":
		return "ivp"
	case "application/vnd.immervision-ivu":
		return "ivu"
	case "application/vnd.insors.igm":
		return "igm"
	case "application/vnd.intercon.formnet":
		return "xpw"
	case "application/vnd.intergeo":
		return "i2g"
	case "application/vnd.intu.qbo":
		return "qbo"
	case "application/vnd.intu.qfx":
		return "qfx"
	case "application/vnd.ipunplugged.rcprofile":
		return "rcprofile"
	case "application/vnd.irepository.package+xml":
		return "irp"
	case "application/vnd.is-xpr":
		return "xpr"
	case "application/vnd.isac.fcs":
		return "fcs"
	case "application/vnd.jam":
		return "jam"
	case "application/vnd.jcp.javame.midlet-rms":
		return "rms"
	case "application/vnd.jisp":
		return "jisp"
	case "application/vnd.joost.joda-archive":
		return "joda"
	case "application/vnd.kahootz":
		return "ktz"
	case "application/vnd.kde.karbon":
		return "karbon"
	case "application/vnd.kde.kchart":
		return "chrt"
	case "application/vnd.kde.kformula":
		return "kfo"
	case "application/vnd.kde.kivio":
		return "flw"
	case "application/vnd.kde.kontour":
		return "kon"
	case "application/vnd.kde.kpresenter":
		return "kpr"
	case "application/vnd.kde.kspread":
		return "ksp"
	case "application/vnd.kde.kword":
		return "kwd"
	case "application/vnd.kenameaapp":
		return "htke"
	case "application/vnd.kidspiration":
		return "kia"
	case "application/vnd.kinar":
		return "kne"
	case "application/vnd.koan":
		return "skp"
	case "application/vnd.kodak-descriptor":
		return "sse"
	case "application/vnd.las.las+xml":
		return "lasxml"
	case "application/vnd.llamagraphics.life-balance.desktop":
		return "lbd"
	case "application/vnd.llamagraphics.life-balance.exchange+xml":
		return "lbe"
	case "application/vnd.lotus-1-2-3":
		return "123"
	case "application/vnd.lotus-approach":
		return "apr"
	case "application/vnd.lotus-freelance":
		return "pre"
	case "application/vnd.lotus-notes":
		return "nsf"
	case "application/vnd.lotus-organizer":
		return "org"
	case "application/vnd.lotus-screencam":
		return "scm"
	case "application/vnd.lotus-wordpro":
		return "lwp"
	case "application/vnd.macports.portpkg":
		return "portpkg"
	case "application/vnd.mcd":
		return "mcd"
	case "application/vnd.medcalcdata":
		return "mc1"
	case "application/vnd.mediastation.cdkey":
		return "cdkey"
	case "application/vnd.mfer":
		return "mwf"
	case "application/vnd.mfmp":
		return "mfm"
	case "application/vnd.micrografx.flo":
		return "flo"
	case "application/vnd.micrografx.igx":
		return "igx"
	case "application/vnd.mif":
		return "mif"
	case "application/vnd.mobius.daf":
		return "daf"
	case "application/vnd.mobius.dis":
		return "dis"
	case "application/vnd.mobius.mbk":
		return "mbk"
	case "application/vnd.mobius.mqy":
		return "mqy"
	case "application/vnd.mobius.msl":
		return "msl"
	case "application/vnd.mobius.plc":
		return "plc"
	case "application/vnd.mobius.txf":
		return "txf"
	case "application/vnd.mophun.application":
		return "mpn"
	case "application/vnd.mophun.certificate":
		return "mpc"
	case "application/vnd.mozilla.xul+xml":
		return "xul"
	case "application/vnd.ms-artgalry":
		return "cil"
	case "application/vnd.ms-cab-compressed":
		return "cab"
	case "application/vnd.ms-excel":
		return "xls"
	case "application/vnd.ms-excel.addin.macroenabled.12":
		return "xlam"
	case "application/vnd.ms-excel.sheet.binary.macroenabled.12":
		return "xlsb"
	case "application/vnd.ms-excel.sheet.macroenabled.12":
		return "xlsm"
	case "application/vnd.ms-excel.template.macroenabled.12":
		return "xltm"
	case "application/vnd.ms-fontobject":
		return "eot"
	case "application/vnd.ms-htmlhelp":
		return "chm"
	case "application/vnd.ms-ims":
		return "ims"
	case "application/vnd.ms-lrm":
		return "lrm"
	case "application/vnd.ms-officetheme":
		return "thmx"
	case "application/vnd.ms-pki.seccat":
		return "cat"
	case "application/vnd.ms-pki.stl":
		return "stl"
	case "application/vnd.ms-powerpoint":
		return "pot"
	case "application/vnd.ms-powerpoint.addin.macroenabled.12":
		return "ppam"
	case "application/vnd.ms-powerpoint.presentation.macroenabled.12":
		return "pptm"
	case "application/vnd.ms-powerpoint.slide.macroenabled.12":
		return "sldm"
	case "application/vnd.ms-powerpoint.slideshow.macroenabled.12":
		return "ppsm"
	case "application/vnd.ms-powerpoint.template.macroenabled.12":
		return "potm"
	case "application/vnd.ms-project":
		return "mpp"
	case "application/vnd.ms-word.document.macroenabled.12":
		return "docm"
	case "application/vnd.ms-word.template.macroenabled.12":
		return "dotm"
	case "application/vnd.ms-works":
		return "wps"
	case "application/vnd.ms-wpl":
		return "wpl"
	case "application/vnd.ms-xpsdocument":
		return "xps"
	case "application/vnd.mseq":
		return "mseq"
	case "application/vnd.musician":
		return "mus"
	case "application/vnd.muvee.style":
		return "msty"
	case "application/vnd.mynfc":
		return "taglet"
	case "application/vnd.neurolanguage.nlu":
		return "nlu"
	case "application/vnd.nitf":
		return "ntf"
	case "application/vnd.noblenet-directory":
		return "nnd"
	case "application/vnd.noblenet-sealer":
		return "nns"
	case "application/vnd.noblenet-web":
		return "nnw"
	case "application/vnd.nokia.n-gage.data":
		return "ngdat"
	case "application/vnd.nokia.n-gage.symbian.install":
		return "n-gage"
	case "application/vnd.nokia.radio-preset":
		return "rpst"
	case "application/vnd.nokia.radio-presets":
		return "rpss"
	case "application/vnd.novadigm.edm":
		return "edm"
	case "application/vnd.novadigm.edx":
		return "edx"
	case "application/vnd.novadigm.ext":
		return "ext"
	case "application/vnd.oasis.opendocument.chart":
		return "odc"
	case "application/vnd.oasis.opendocument.chart-template":
		return "otc"
	case "application/vnd.oasis.opendocument.database":
		return "odb"
	case "application/vnd.oasis.opendocument.formula":
		return "odf"
	case "application/vnd.oasis.opendocument.formula-template":
		return "odft"
	case "application/vnd.oasis.opendocument.graphics":
		return "odg"
	case "application/vnd.oasis.opendocument.graphics-template":
		return "otg"
	case "application/vnd.oasis.opendocument.image":
		return "odi"
	case "application/vnd.oasis.opendocument.image-template":
		return "oti"
	case "application/vnd.oasis.opendocument.presentation":
		return "odp"
	case "application/vnd.oasis.opendocument.presentation-template":
		return "otp"
	case "application/vnd.oasis.opendocument.spreadsheet":
		return "ods"
	case "application/vnd.oasis.opendocument.spreadsheet-template":
		return "ots"
	case "application/vnd.oasis.opendocument.text":
		return "odt"
	case "application/vnd.oasis.opendocument.text-master":
		return "odm"
	case "application/vnd.oasis.opendocument.text-template":
		return "ott"
	case "application/vnd.oasis.opendocument.text-web":
		return "oth"
	case "application/vnd.olpc-sugar":
		return "xo"
	case "application/vnd.oma.dd2+xml":
		return "dd2"
	case "application/vnd.openofficeorg.extension":
		return "oxt"
	case "application/vnd.openxmlformats-officedocument.presentationml.presentation":
		return "pptx"
	case "application/vnd.openxmlformats-officedocument.presentationml.slide":
		return "sldx"
	case "application/vnd.openxmlformats-officedocument.presentationml.slideshow":
		return "ppsx"
	case "application/vnd.openxmlformats-officedocument.presentationml.template":
		return "potx"
	case "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
		return "xlsx"
	case "application/vnd.openxmlformats-officedocument.spreadsheetml.template":
		return "xltx"
	case "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
		return "docx"
	case "application/vnd.openxmlformats-officedocument.wordprocessingml.template":
		return "dotx"
	case "application/vnd.osgeo.mapguide.package":
		return "mgp"
	case "application/vnd.osgi.dp":
		return "dp"
	case "application/vnd.osgi.subsystem":
		return "esa"
	case "application/vnd.palm":
		return "pdb"
	case "application/vnd.pawaafile":
		return "paw"
	case "application/vnd.pg.format":
		return "str"
	case "application/vnd.pg.osasli":
		return "ei6"
	case "application/vnd.picsel":
		return "efif"
	case "application/vnd.pmi.widget":
		return "wg"
	case "application/vnd.pocketlearn":
		return "plf"
	case "application/vnd.powerbuilder6":
		return "pbd"
	case "application/vnd.previewsystems.box":
		return "box"
	case "application/vnd.proteus.magazine":
		return "mgz"
	case "application/vnd.publishare-delta-tree":
		return "qps"
	case "application/vnd.pvi.ptid1":
		return "ptid"
	case "application/vnd.quark.quarkxpress":
		return "qxd"
	case "application/vnd.realvnc.bed":
		return "bed"
	case "application/vnd.recordare.musicxml":
		return "mxl"
	case "application/vnd.recordare.musicxml+xml":
		return "musicxml"
	case "application/vnd.rig.cryptonote":
		return "cryptonote"
	case "application/vnd.rim.cod":
		return "cod"
	case "application/vnd.rn-realmedia":
		return "rm"
	case "application/vnd.rn-realmedia-vbr":
		return "rmvb"
	case "application/vnd.route66.link66+xml":
		return "link66"
	case "application/vnd.sailingtracker.track":
		return "st"
	case "application/vnd.seemail":
		return "see"
	case "application/vnd.sema":
		return "sema"
	case "application/vnd.semd":
		return "semd"
	case "application/vnd.semf":
		return "semf"
	case "application/vnd.shana.informed.formdata":
		return "ifm"
	case "application/vnd.shana.informed.formtemplate":
		return "itp"
	case "application/vnd.shana.informed.interchange":
		return "iif"
	case "application/vnd.shana.informed.package":
		return "ipk"
	case "application/vnd.simtech-mindmapper":
		return "twd"
	case "application/vnd.smaf":
		return "mmf"
	case "application/vnd.smart.teacher":
		return "teacher"
	case "application/vnd.solent.sdkm+xml":
		return "sdkm"
	case "application/vnd.spotfire.dxp":
		return "dxp"
	case "application/vnd.spotfire.sfs":
		return "sfs"
	case "application/vnd.stardivision.calc":
		return "sdc"
	case "application/vnd.stardivision.draw":
		return "sda"
	case "application/vnd.stardivision.impress":
		return "sdp"
	case "application/vnd.stardivision.math":
		return "sdf"
	case "application/vnd.stardivision.writer":
		return "vor"
	case "application/vnd.stardivision.writer-global":
		return "sgl"
	case "application/vnd.stepmania.package":
		return "smzip"
	case "application/vnd.stepmania.stepchart":
		return "sm"
	case "application/vnd.sun.xml.calc":
		return "sxc"
	case "application/vnd.sun.xml.calc.template":
		return "stc"
	case "application/vnd.sun.xml.draw":
		return "sxd"
	case "application/vnd.sun.xml.draw.template":
		return "std"
	case "application/vnd.sun.xml.impress":
		return "sxi"
	case "application/vnd.sun.xml.impress.template":
		return "sti"
	case "application/vnd.sun.xml.math":
		return "sxm"
	case "application/vnd.sun.xml.writer":
		return "sxw"
	case "application/vnd.sun.xml.writer.global":
		return "sxg"
	case "application/vnd.sun.xml.writer.template":
		return "stw"
	case "application/vnd.sus-calendar":
		return "sus"
	case "application/vnd.svd":
		return "svd"
	case "application/vnd.symbian.install":
		return "sis"
	case "application/vnd.syncml+xml":
		return "xsm"
	case "application/vnd.syncml.dm+wbxml":
		return "bdm"
	case "application/vnd.syncml.dm+xml":
		return "xdm"
	case "application/vnd.tao.intent-module-archive":
		return "tao"
	case "application/vnd.tcpdump.pcap":
		return "cap"
	case "application/vnd.tmobile-livetv":
		return "tmo"
	case "application/vnd.trid.tpt":
		return "tpt"
	case "application/vnd.triscape.mxs":
		return "mxs"
	case "application/vnd.trueapp":
		return "tra"
	case "application/vnd.ufdl":
		return "ufd"
	case "application/vnd.uiq.theme":
		return "utz"
	case "application/vnd.umajin":
		return "umj"
	case "application/vnd.unity":
		return "unityweb"
	case "application/vnd.uoml+xml":
		return "uoml"
	case "application/vnd.vcx":
		return "vcx"
	case "application/vnd.visio":
		return "vsd"
	case "application/vnd.visionary":
		return "vis"
	case "application/vnd.vsf":
		return "vsf"
	case "application/vnd.wap.wbxml":
		return "wbxml"
	case "application/vnd.wap.wmlc":
		return "wmlc"
	case "application/vnd.wap.wmlscriptc":
		return "wmlsc"
	case "application/vnd.webturbo":
		return "wtb"
	case "application/vnd.wolfram.player":
		return "nbp"
	case "application/vnd.wordperfect":
		return "wpd"
	case "application/vnd.wqd":
		return "wqd"
	case "application/vnd.wt.stf":
		return "stf"
	case "application/vnd.xara":
		return "xar"
	case "application/vnd.xfdl":
		return "xfdl"
	case "application/vnd.yamaha.hv-dic":
		return "hvd"
	case "application/vnd.yamaha.hv-script":
		return "hvs"
	case "application/vnd.yamaha.hv-voice":
		return "hvp"
	case "application/vnd.yamaha.openscoreformat":
		return "osf"
	case "application/vnd.yamaha.openscoreformat.osfpvg+xml":
		return "osfpvg"
	case "application/vnd.yamaha.smaf-audio":
		return "saf"
	case "application/vnd.yamaha.smaf-phrase":
		return "spf"
	case "application/vnd.yellowriver-custom-menu":
		return "cmp"
	case "application/vnd.zul":
		return "zir"
	case "application/vnd.zzazz.deck+xml":
		return "zaz"
	case "application/voicexml+xml":
		return "vxml"
	case "application/widget":
		return "wgt"
	case "application/winhlp":
		return "hlp"
	case "application/wsdl+xml":
		return "wsdl"
	case "application/wspolicy+xml":
		return "wspolicy"
	case "application/x-7z-compressed":
		return "7z"
	case "application/x-abiword":
		return "abw"
	case "application/x-ace-compressed":
		return "ace"
	case "application/x-apple-diskimage":
		return "dmg"
	case "application/x-authorware-bin":
		return "aab"
	case "application/x-authorware-map":
		return "aam"
	case "application/x-authorware-seg":
		return "aas"
	case "application/x-bcpio":
		return "bcpio"
	case "application/x-bittorrent":
		return "torrent"
	case "application/x-blorb":
		return "blb"
	case "application/x-bzip":
		return "bz"
	case "application/x-bzip2":
		return "bz2"
	case "application/x-cbr":
		return "cbr"
	case "application/x-cdlink":
		return "vcd"
	case "application/x-cfs-compressed":
		return "cfs"
	case "application/x-chat":
		return "chat"
	case "application/x-chess-pgn":
		return "pgn"
	case "application/x-conference":
		return "nsc"
	case "application/x-cpio":
		return "cpio"
	case "application/x-csh":
		return "csh"
	case "application/x-debian-package":
		return "deb"
	case "application/x-dgc-compressed":
		return "dgc"
	case "application/x-director":
		return "dcr"
	case "application/x-doom":
		return "wad"
	case "application/x-dtbncx+xml":
		return "ncx"
	case "application/x-dtbook+xml":
		return "dtb"
	case "application/x-dtbresource+xml":
		return "res"
	case "application/x-dvi":
		return "dvi"
	case "application/x-envoy":
		return "evy"
	case "application/x-eva":
		return "eva"
	case "application/x-font-bdf":
		return "bdf"
	case "application/x-font-ghostscript":
		return "gsf"
	case "application/x-font-linux-psf":
		return "psf"
	case "application/x-font-pcf":
		return "pcf"
	case "application/x-font-snf":
		return "snf"
	case "application/x-font-type1":
		return "pfa"
	case "application/x-freearc":
		return "arc"
	case "application/x-futuresplash":
		return "spl"
	case "application/x-gca-compressed":
		return "gca"
	case "application/x-glulx":
		return "ulx"
	case "application/x-gnumeric":
		return "gnumeric"
	case "application/x-gramps-xml":
		return "gramps"
	case "application/x-gtar":
		return "gtar"
	case "application/x-hdf":
		return "hdf"
	case "application/x-install-instructions":
		return "install"
	case "application/x-iso9660-image":
		return "iso"
	case "application/x-java-jnlp-file":
		return "jnlp"
	case "application/x-latex":
		return "latex"
	case "application/x-lzh-compressed":
		return "lzh"
	case "application/x-mie":
		return "mie"
	case "application/x-mobipocket-ebook":
		return "prc"
	case "application/x-ms-application":
		return "application"
	case "application/x-ms-shortcut":
		return "lnk"
	case "application/x-ms-wmd":
		return "wmd"
	case "application/x-ms-wmz":
		return "wmz"
	case "application/x-ms-xbap":
		return "xbap"
	case "application/x-msaccess":
		return "mdb"
	case "application/x-msbinder":
		return "obd"
	case "application/x-mscardfile":
		return "crd"
	case "application/x-msclip":
		return "clp"
	case "application/x-msdownload":
		return "exe"
	case "application/x-msmediaview":
		return "mvb"
	case "application/x-msmetafile":
		return "wmf"
	case "application/x-msmoney":
		return "mny"
	case "application/x-mspublisher":
		return "pub"
	case "application/x-msschedule":
		return "scd"
	case "application/x-msterminal":
		return "trm"
	case "application/x-mswrite":
		return "wri"
	case "application/x-netcdf":
		return "nc"
	case "application/x-nzb":
		return "nzb"
	case "application/x-pkcs12":
		return "p12"
	case "application/x-pkcs7-certificates":
		return "p7b"
	case "application/x-pkcs7-certreqresp":
		return "p7r"
	case "application/x-rar-compressed":
		return "rar"
	case "application/x-research-info-systems":
		return "ris"
	case "application/x-sh":
		return "sh"
	case "application/x-shar":
		return "shar"
	case "application/x-shockwave-flash":
		return "swf"
	case "application/x-silverlight-app":
		return "xap"
	case "application/x-sql":
		return "sql"
	case "application/x-stuffit":
		return "sit"
	case "application/x-stuffitx":
		return "sitx"
	case "application/x-subrip":
		return "srt"
	case "application/x-sv4cpio":
		return "sv4cpio"
	case "application/x-sv4crc":
		return "sv4crc"
	case "application/x-t3vm-image":
		return "t3"
	case "application/x-tads":
		return "gam"
	case "application/x-tar":
		return "tar"
	case "application/x-tcl":
		return "tcl"
	case "application/x-tex":
		return "tex"
	case "application/x-tex-tfm":
		return "tfm"
	case "application/x-texinfo":
		return "texinfo"
	case "application/x-tgif":
		return "obj"
	case "application/x-ustar":
		return "ustar"
	case "application/x-wais-source":
		return "src"
	case "application/x-x509-ca-cert":
		return "crt"
	case "application/x-xfig":
		return "fig"
	case "application/x-xliff+xml":
		return "xlf"
	case "application/x-xpinstall":
		return "xpi"
	case "application/x-xz":
		return "xz"
	case "application/x-zmachine":
		return "z1"
	case "application/xaml+xml":
		return "xaml"
	case "application/xcap-diff+xml":
		return "xdf"
	case "application/xenc+xml":
		return "xenc"
	case "application/xhtml+xml":
		return "xhtml"
	case "application/xml":
		return "xml"
	case "application/xml-dtd":
		return "dtd"
	case "application/xop+xml":
		return "xop"
	case "application/xproc+xml":
		return "xpl"
	case "application/xslt+xml":
		return "xsl"
	case "application/xspf+xml":
		return "xspf"
	case "application/xv+xml":
		return "mxml"
	case "application/yang":
		return "yang"
	case "application/yin+xml":
		return "yin"
	case "application/zip":
		return "zip"
	case "audio/adpcm":
		return "adp"
	case "audio/basic":
		return "snd"
	case "audio/midi":
		return "rtx"
	case "audio/mp4":
		return "m4a"
	case "audio/mpeg":
		return "mp3"
	case "audio/ogg":
		return "oga"
	case "audio/s3m":
		return "s3m"
	case "audio/silk":
		return "sil"
	case "audio/vnd.dece.audio":
		return "uva"
	case "audio/vnd.digital-winds":
		return "eol"
	case "audio/vnd.dra":
		return "dra"
	case "audio/vnd.dts":
		return "dts"
	case "audio/vnd.dts.hd":
		return "dtshd"
	case "audio/vnd.lucent.voice":
		return "lvp"
	case "audio/vnd.ms-playready.media.pya":
		return "pya"
	case "audio/vnd.nuera.ecelp4800":
		return "ecelp4800"
	case "audio/vnd.nuera.ecelp7470":
		return "ecelp7470"
	case "audio/vnd.nuera.ecelp9600":
		return "ecelp9600"
	case "audio/vnd.rip":
		return "rip"
	case "audio/webm":
		return "weba"
	case "audio/x-aac":
		return "aac"
	case "audio/x-aiff":
		return "aif"
	case "audio/x-caf":
		return "caf"
	case "audio/x-flac":
		return "flac"
	case "audio/x-matroska":
		return "mka"
	case "audio/x-mpegurl":
		return "m3u"
	case "audio/x-ms-wax":
		return "wax"
	case "audio/x-ms-wma":
		return "wma"
	case "audio/x-pn-realaudio":
		return "ra"
	case "audio/x-pn-realaudio-plugin":
		return "rmp"
	case "audio/x-wav":
		return "wav"
	case "audio/xm":
		return "xm"
	case "chemical/x-cdx":
		return "cdx"
	case "chemical/x-cif":
		return "cif"
	case "chemical/x-cmdf":
		return "cmdf"
	case "chemical/x-cml":
		return "cml"
	case "chemical/x-csml":
		return "csml"
	case "chemical/x-xyz":
		return "xyz"
	case "font/collection":
		return "ttc"
	case "font/otf":
		return "ttf"
	case "font/ttf":
		return "ttf"
	case "font/woff":
		return "woff"
	case "font/woff2":
		return "woff2"
	case "image/bmp":
		return "bmp"
	case "image/cgm":
		return "cgm"
	case "image/g3fax":
		return "g3"
	case "image/gif":
		return "gif"
	case "image/ief":
		return "ief"
	case "image/jpeg":
		return "jpg"
	case "image/ktx":
		return "ktx"
	case "image/png":
		return "png"
	case "image/prs.btif":
		return "btif"
	case "image/sgi":
		return "sgi"
	case "image/svg+xml":
		return "svg"
	case "image/tiff":
		return "tiff"
	case "image/vnd.adobe.photoshop":
		return "psd"
	case "image/vnd.dece.graphic":
		return "uvi"
	case "image/vnd.djvu":
		return "djvu"
	case "image/vnd.dvb.subtitle":
		return "sub"
	case "image/vnd.dwg":
		return "dwg"
	case "image/vnd.dxf":
		return "dxf"
	case "image/vnd.fastbidsheet":
		return "fbs"
	case "image/vnd.fpx":
		return "fpx"
	case "image/vnd.fst":
		return "fst"
	case "image/vnd.fujixerox.edmics-mmr":
		return "mmr"
	case "image/vnd.fujixerox.edmics-rlc":
		return "rlc"
	case "image/vnd.ms-modi":
		return "mdi"
	case "image/vnd.ms-photo":
		return "wdp"
	case "image/vnd.net-fpx":
		return "npx"
	case "image/vnd.wap.wbmp":
		return "wbmp"
	case "image/vnd.xiff":
		return "xif"
	case "image/webp":
		return "webp"
	case "image/x-3ds":
		return "3ds"
	case "image/x-cmu-raster":
		return "ras"
	case "image/x-cmx":
		return "cmx"
	case "image/x-freehand":
		return "fh"
	case "image/x-icon":
		return "ico"
	case "image/x-mrsid-image":
		return "sid"
	case "image/x-pcx":
		return "pcx"
	case "image/x-pict":
		return "pic"
	case "image/x-portable-anymap":
		return "pnm"
	case "image/x-portable-bitmap":
		return "pbm"
	case "image/x-portable-graymap":
		return "pgm"
	case "image/x-portable-pixmap":
		return "ppm"
	case "image/x-rgb":
		return "rgb"
	case "image/x-tga":
		return "tga"
	case "image/x-xbitmap":
		return "xbm"
	case "image/x-xpixmap":
		return "xpm"
	case "image/x-xwindowdump":
		return "xwd"
	case "message/rfc822":
		return "eml"
	case "model/iges":
		return "igs"
	case "model/mesh":
		return "msh"
	case "model/vnd.collada+xml":
		return "dae"
	case "model/vnd.dwf":
		return "dwf"
	case "model/vnd.gdl":
		return "gdl"
	case "model/vnd.gtw":
		return "gtw"
	case "model/vnd.mts":
		return "mts"
	case "model/vnd.vtu":
		return "vtu"
	case "model/vrml":
		return "wrl"
	case "model/x3d+binary":
		return "x3db"
	case "model/x3d+vrml":
		return "x3dv"
	case "model/x3d+xml":
		return "x3d"
	case "text/cache-manifest":
		return "appcache"
	case "text/calendar":
		return "ics"
	case "text/css":
		return "css"
	case "text/csv":
		return "csv"
	case "text/html":
		return "html"
	case "text/n3":
		return "n3"
	case "text/plain":
		return "txt"
	case "text/prs.lines.tag":
		return "dsc"
	case "text/richtext":
		return "rtx"
	case "text/sgml":
		return "sgml"
	case "text/tab-separated-values":
		return "tsv"
	case "text/troff":
		return "t"
	case "text/turtle":
		return "ttl"
	case "text/uri-list":
		return "uri"
	case "text/vcard":
		return "vcf"
	case "text/vnd.curl":
		return "curl"
	case "text/vnd.curl.dcurl":
		return "dcurl"
	case "text/vnd.curl.mcurl":
		return "mcurl"
	case "text/vnd.curl.scurl":
		return "scurl"
	case "text/vnd.dvb.subtitle":
		return "sub"
	case "text/vnd.fly":
		return "fly"
	case "text/vnd.fmi.flexstor":
		return "flx"
	case "text/vnd.graphviz":
		return "gv"
	case "text/vnd.in3d.3dml":
		return "3dml"
	case "text/vnd.in3d.spot":
		return "spot"
	case "text/vnd.sun.j2me.app-descriptor":
		return "jad"
	case "text/vnd.wap.wml":
		return "wml"
	case "text/vnd.wap.wmlscript":
		return "wmls"
	case "text/x-asm":
		return "s"
	case "text/x-c":
		return "c"
	case "text/x-fortran":
		return "f"
	case "text/x-java-source":
		return "java"
	case "text/x-nfo":
		return "nfo"
	case "text/x-opml":
		return "opml"
	case "text/x-pascal":
		return "p"
	case "text/x-setext":
		return "etx"
	case "text/x-sfv":
		return "sfv"
	case "text/x-uuencode":
		return "uu"
	case "text/x-vcalendar":
		return "vcs"
	case "text/x-vcard":
		return "vcf"
	case "video/3gpp":
		return "3gpp"
	case "video/3gpp2":
		return "3gpp2"
	case "video/h261":
		return "h261"
	case "video/h263":
		return "h263"
	case "video/h264":
		return "h264"
	case "video/jpeg":
		return "jpgv"
	case "video/jpm":
		return "jpm"
	case "video/mj2":
		return "mj2"
	case "video/mp4":
		return "mp4"
	case "video/mpeg":
		return "mpeg"
	case "video/ogg":
		return "ogv"
	case "video/quicktime":
		return "mov"
	case "video/vnd.dece.hd":
		return "uvh"
	case "video/vnd.dece.mobile":
		return "uvm"
	case "video/vnd.dece.pd":
		return "uvp"
	case "video/vnd.dece.sd":
		return "uvs"
	case "video/vnd.dece.video":
		return "uvv"
	case "video/vnd.dvb.file":
		return "dvb"
	case "video/vnd.fvt":
		return "fvt"
	case "video/vnd.mpegurl":
		return "mxu"
	case "video/vnd.ms-playready.media.pyv":
		return "pyv"
	case "video/vnd.uvvu.mp4":
		return "uvu"
	case "video/vnd.vivo":
		return "viv"
	case "video/webm":
		return "webm"
	case "video/x-f4v":
		return "f4v"
	case "video/x-fli":
		return "fli"
	case "video/x-flv":
		return "flv"
	case "video/x-m4v":
		return "m4v"
	case "video/x-matroska":
		return "mkv"
	case "video/x-mng":
		return "mng"
	case "video/x-ms-asf":
		return "asf"
	case "video/x-ms-vob":
		return "vob"
	case "video/x-ms-wm":
		return "wm"
	case "video/x-ms-wmv":
		return "wmv"
	case "video/x-ms-wmx":
		return "wmx"
	case "video/x-ms-wvx":
		return "wvx"
	case "video/x-msvideo":
		return "avi"
	case "video/x-sgi-movie":
		return "movie"
	case "video/x-smv":
		return "smv"
	case "x-conference/x-cooltalk":
		return "ice"
	case "application/annodex":
		return "anx"
	case "application/atomserv+xml":
		return "atomsrv"
	case "application/bbolin":
		return "lin"
	case "application/dicom":
		return "dcm"
	case "application/dsptype":
		return "tsp"
	case "application/font-sfnt":
		return "otf"
	case "application/font-woff":
		return "woff"
	case "application/futuresplash":
		return "spl"
	case "application/gzip":
		return "gz"
	case "application/hta":
		return "hta"
	case "application/m3g":
		return "m3g"
	case "application/msaccess":
		return "mdb"
	case "application/pgp-keys":
		return "key"
	case "application/rar":
		return "rar"
	case "application/sla":
		return "stl"
	case "application/vnd.debian.binary-package":
		return "deb"
	case "application/vnd.font-fontforge-sfd":
		return "sfd"
	case "application/vnd.stardivision.chart":
		return "sds"
	case "application/vnd.wordperfect5.1":
		return "wp5"
	case "application/x-123":
		return "wk"
	case "application/x-cab":
		return "cab"
	case "application/x-cbz":
		return "cbz"
	case "application/x-cdf":
		return "cdf"
	case "application/x-comsol":
		return "mph"
	case "application/x-dms":
		return "dms"
	case "application/x-font":
		return "pcf"
	case "application/x-freemind":
		return "mm"
	case "application/x-ganttproject":
		return "gan"
	case "application/x-go-sgf":
		return "sgf"
	case "application/x-graphing-calculator":
		return "gcf"
	case "application/x-gtar-compressed":
		return "tgz"
	case "application/x-hwp":
		return "hwp"
	case "application/x-ica":
		return "ica"
	case "application/x-info":
		return "info"
	case "application/x-internet-signup":
		return "ins"
	case "application/x-iphone":
		return "iii"
	case "application/x-jam":
		return "jam"
	case "application/x-jmol":
		return "jmz"
	case "application/x-kchart":
		return "chrt"
	case "application/x-killustrator":
		return "kil"
	case "application/x-koan":
		return "skp"
	case "application/x-kpresenter":
		return "kpr"
	case "application/x-kspread":
		return "ksp"
	case "application/x-kword":
		return "kwd"
	case "application/x-lha":
		return "lha"
	case "application/x-lyx":
		return "lyx"
	case "application/x-lzh":
		return "lzh"
	case "application/x-lzx":
		return "lzx"
	case "application/x-maker":
		return "frm"
	case "application/x-mif":
		return "mif"
	case "application/x-mpegurl":
		return "m3u"
	case "application/x-ms-manifest":
		return "manifest"
	case "application/x-msdos-program":
		return "com"
	case "application/x-msi":
		return "msi"
	case "application/x-ns-proxy-autoconfig":
		return "pac"
	case "application/x-nwc":
		return "nwc"
	case "application/x-object":
		return "o"
	case "application/x-oz-application":
		return "oza"
	case "application/x-pkcs7-crl":
		return "crl"
	case "application/x-python-code":
		return "pyc"
	case "application/x-qgis":
		return "qgs"
	case "application/x-quicktimeplayer":
		return "qtl"
	case "application/x-rdp":
		return "rdp"
	case "application/x-redhat-package-manager":
		return "rpm"
	case "application/x-rss+xml":
		return "rss"
	case "application/x-ruby":
		return "rb"
	case "application/x-scilab":
		return "sci"
	case "application/x-scilab-xcos":
		return "xcos"
	case "application/x-silverlight":
		return "scr"
	case "application/x-tex-gf":
		return "gf"
	case "application/x-tex-pk":
		return "pk"
	case "application/x-trash":
		return "~"
	case "application/x-troff":
		return "t"
	case "application/x-troff-man":
		return "man"
	case "application/x-troff-me":
		return "me"
	case "application/x-troff-ms":
		return "ms"
	case "application/x-wingz":
		return "wz"
	case "application/x-xcf":
		return "xcf"
	case "audio/amr":
		return "amr"
	case "audio/amr-wb":
		return "awb"
	case "audio/annodex":
		return "axa"
	case "audio/csound":
		return "csd"
	case "audio/flac":
		return "flac"
	case "audio/mpegurl":
		return "m3u"
	case "audio/prs.sid":
		return "sid"
	case "audio/x-gsm":
		return "gsm"
	case "audio/x-realaudio":
		return "ra"
	case "audio/x-scpls":
		return "pls"
	case "audio/x-sd2":
		return "sd2"
	case "chemical/x-alchemy":
		return "alc"
	case "chemical/x-cache":
		return "cac"
	case "chemical/x-cache-csf":
		return "csf"
	case "chemical/x-cactvs-binary":
		return "cbin"
	case "chemical/x-cerius":
		return "cer"
	case "chemical/x-chem3d":
		return "c3d"
	case "chemical/x-chemdraw":
		return "chm"
	case "chemical/x-compass":
		return "cpa"
	case "chemical/x-crossfire":
		return "bsd"
	case "chemical/x-ctx":
		return "ctx"
	case "chemical/x-cxf":
		return "cxf"
	case "chemical/x-embl-dl-nucleotide":
		return "emb"
	case "chemical/x-galactic-spc":
		return "spc"
	case "chemical/x-gamess-input":
		return "inp"
	case "chemical/x-gaussian-checkpoint":
		return "fch"
	case "chemical/x-gaussian-cube":
		return "cub"
	case "chemical/x-gaussian-input":
		return "gau"
	case "chemical/x-gaussian-log":
		return "gal"
	case "chemical/x-gcg8-sequence":
		return "gcg"
	case "chemical/x-genbank":
		return "gen"
	case "chemical/x-hin":
		return "hin"
	case "chemical/x-isostar":
		return "istr"
	case "chemical/x-jcamp-dx":
		return "jdx"
	case "chemical/x-kinemage":
		return "kin"
	case "chemical/x-macmolecule":
		return "mcm"
	case "chemical/x-macromodel-input":
		return "mmd"
	case "chemical/x-mdl-molfile":
		return "mol"
	case "chemical/x-mdl-rdfile":
		return "rd"
	case "chemical/x-mdl-rxnfile":
		return "rxn"
	case "chemical/x-mdl-sdfile":
		return "sd"
	case "chemical/x-mdl-tgf":
		return "tgf"
	case "chemical/x-mmcif":
		return "mcif"
	case "chemical/x-mol2":
		return "mol2"
	case "chemical/x-molconn-z":
		return "b"
	case "chemical/x-mopac-graph":
		return "gpt"
	case "chemical/x-mopac-input":
		return "mop"
	case "chemical/x-mopac-out":
		return "moo"
	case "chemical/x-mopac-vib":
		return "mvb"
	case "chemical/x-ncbi-asn1":
		return "asn"
	case "chemical/x-ncbi-asn1-ascii":
		return "prt"
	case "chemical/x-ncbi-asn1-binary":
		return "val"
	case "chemical/x-ncbi-asn1-spec":
		return "asn"
	case "chemical/x-pdb":
		return "pdb"
	case "chemical/x-rosdal":
		return "ros"
	case "chemical/x-swissprot":
		return "sw"
	case "chemical/x-vamas-iso14976":
		return "vms"
	case "chemical/x-vmd":
		return "vmd"
	case "chemical/x-xtel":
		return "xtel"
	case "font/sfnt":
		return "ttf"
	case "image/jp2":
		return "jp2"
	case "image/jpm":
		return "jpm"
	case "image/jpx":
		return "jpx"
	case "image/pcx":
		return "pcx"
	case "image/vnd.microsoft.icon":
		return "ico"
	case "image/x-canon-cr2":
		return "cr2"
	case "image/x-canon-crw":
		return "crw"
	case "image/x-coreldraw":
		return "cdr"
	case "image/x-coreldrawpattern":
		return "pat"
	case "image/x-coreldrawtemplate":
		return "cdt"
	case "image/x-corelphotopaint":
		return "cpt"
	case "image/x-epson-erf":
		return "erf"
	case "image/x-jg":
		return "art"
	case "image/x-jng":
		return "jng"
	case "image/x-ms-bmp":
		return "bmp"
	case "image/x-nikon-nef":
		return "nef"
	case "image/x-olympus-orf":
		return "orf"
	case "image/x-photoshop":
		return "psd"
	case "text/h323":
		return "323"
	case "text/iuls":
		return "uls"
	case "text/mathml":
		return "mml"
	case "text/markdown":
		return "md"
	case "text/scriptlet":
		return "sct"
	case "text/texmacs":
		return "tm"
	case "text/x-bibtex":
		return "bib"
	case "text/x-boo":
		return "boo"
	case "text/x-c++hdr":
		return "hpp"
	case "text/x-c++src":
		return "cpp"
	case "text/x-chdr":
		return "h"
	case "text/x-component":
		return "htc"
	case "text/x-csh":
		return "csh"
	case "text/x-csrc":
		return "c"
	case "text/x-dsrc":
		return "d"
	case "text/x-diff":
		return "diff"
	case "text/x-haskell":
		return "hs"
	case "text/x-java":
		return "java"
	case "text/x-lilypond":
		return "ly"
	case "text/x-literate-haskell":
		return "lhs"
	case "text/x-moc":
		return "moc"
	case "text/x-pcs-gcd":
		return "gcd"
	case "text/x-perl":
		return "pl"
	case "text/x-python":
		return "py"
	case "text/x-scala":
		return "scala"
	case "text/x-sh":
		return "sh"
	case "text/x-tcl":
		return "tcl"
	case "text/x-tex":
		return "tex"
	case "video/annodex":
		return "axv"
	case "video/dl":
		return "dl"
	case "video/dv":
		return "dif"
	case "video/fli":
		return "fli"
	case "video/gl":
		return "gl"
	case "video/mp2t":
		return "ts"
	case "video/x-la-asf":
		return "lsf"
	case "x-epoc/x-sisx-app":
		return "sisx"
	case "x-world/x-vrml":
		return "vrm"
	case "application/vnd.youtube.yt":
		return "yt"
	case "application/x-android-drm-fl":
		return "fl"
	case "application/x-flac":
		return "flac"
	case "application/x-pem-file":
		return "pem"
	case "application/x-webarchive":
		return "webarchive"
	case "application/x-webarchive-xml":
		return "webarchivexml"
	case "application/x-x509-server-cert":
		return "crt"
	case "application/x-x509-user-cert":
		return "crt"
	case "audio/3gpp":
		return "3gpp"
	case "audio/aac-adts":
		return "aac"
	case "audio/imelody":
		return "imy"
	case "audio/mobile-xmf":
		return "mxmf"
	case "audio/sp-midi":
		return "smf"
	case "image/heic":
		return "heic"
	case "image/heic-sequence":
		return "heics"
	case "image/heif":
		return "heif"
	case "image/heif-sequence":
		return "heifs"
	case "image/ico":
		return "cur"
	case "image/x-adobe-dng":
		return "dng"
	case "image/x-fuji-raf":
		return "raf"
	case "image/x-nikon-nrw":
		return "nrw"
	case "image/x-panasonic-rw2":
		return "rw2"
	case "image/x-pentax-pef":
		return "pef"
	case "image/x-samsung-srw":
		return "srw"
	case "image/x-sony-arw":
		return "arw"
	case "text/comma-separated-values":
		return "csv"
	case "text/rtf":
		return "rtf"
	case "text/text":
		return "phps"
	case "text/xml":
		return "xml"
	case "video/avi":
		return "avi"
	case "video/m4v":
		return "m4v"
	case "video/mp2p":
		return "mpeg"
	case "video/mp2ts":
		return "ts"
	case "video/x-webex":
		return "wrf"
	case "audio/aac":
		return "aac"
	default:
		return nil
	}
}
